---
title: "R Notebook"
output: html_notebook
---
#Schools Comparison
```{r}
library(shiny)
library(plotly)
library(ggplot2)
library(leaflet)

############################### Schools Comparision###############################################
ui <- fluidPage(
  titlePanel( 'Compare Data for Multiple Schools'),
  sidebarLayout(
    sidebarPanel(
        checkboxGroupInput(inputId = 'show_schools', 
                           label = 'Schools to compare:',
                           choices = as.character(colnames(t.schools2014)), 
                           selected = as.character(colnames(t.schools2014)[c(1,2)]), 
                           width = "200px"
      )
    ),
    mainPanel(
      tabsetPanel(
        id = 'criminal.offenses',
        tabPanel('Criminal Offenses', 
                 DT::dataTableOutput('criminal.offenses'),
                 plotOutput("rate.bar"),
                 plotOutput("schoolTrend")))
      )
    )
  )

server <- function(input, output) {
  
  school <- t.schools2014
  schools.selected <- reactive({school[, input$show_schools, drop = FALSE]})
  
  
  output$criminal.offenses <- DT::renderDataTable({
    DT::datatable(schools.selected(), 
                  extensions = 'Buttons', 
                  options = list(pageLength = 25, dom = 'Bfrtip', buttons = I('colvis')),
                  class = "display")
  })
  
  
  output$rate.bar <- renderPlot({
    
    barplot(as.matrix(schools.selected()[dim(schools.selected())[1],]), 
            col = "pink", xlab = "Schools", ylab = "Crime Rate")
    })
  
  school.names <- reactive( {unique(input$show_schools)})
  output$schoolTrend <- renderPlot({
    xrange <- range(agg1$Group.1) 
    yrange <- c(0,500)
    plot(xrange, yrange, type="n", xlab="Years",ylab="Total Crimes")
    for(i in 1:length(school.names())){
        d <- subset( agg1, agg1$Group.2 == school.names()[i] )
        lines(d$Group.1, d$total, col = i)
        legend("topright", col = c(1:length(school.names())),
                legend = school.names(), lty = rep(1,length(school.names())))
    }
      
  })
}

shinyApp(ui = ui, server = server)
```
#Trend
```{r}
###################################### Trend ######################################################
ui <- fluidPage(
  sidebarLayout(
    sidebarPanel(
      selectInput("type", "Choose a type:",
                  as.character(names(agg))[-1],
                  as.character(names(agg))[15])
    ),
    mainPanel(
      tabsetPanel(
     
      tabPanel('Crimes Trend', plotlyOutput("trend"))
      
      )
    )
  )
)
server <- function(input, output){
  
  output$trend <- renderPlotly({
    plot_ly(agg, x = c(2001:2014), y = agg[,input$type], mode = "line")
  })
  
  
}

shinyApp(ui = ui, server = server)
```

#School pick map
```{r}
################################### Schools leaflet #############################################
ui <- fluidPage(
 titlePanel( 'Choose Multiple Schools'),
  sidebarLayout(
    sidebarPanel(
        selectInput(inputId = 'states', 
                           label = 'Your state:',
                           choices = as.character(unique(new_campus$state)), 
                           selected = as.character(unique(new_campus$state)[1]), 
                           width = "200px"
      )
    ),
    mainPanel(
      leaflet("campus_map")
      )
    )
)

server <- function(input, output){
  output$school_map <- renderLeaflet({
      leaflet(new_campus) %>%
        addTiles() %>% 
  addMarkers(lng=new_campus[,2], lat=new_campus[,3], 
             popup=paste(as.character(new_campus[,1]),
                         as.character(new_campus[,7]), sep = ", "),
             clusterOptions = markerClusterOptions(freezeAtZoom = 10))
  })
}

shinyApp(ui, server)
```
#Combination
```{r}






plot(x = agg1$Group.1[agg1$Group.2 == school.names()[1]], 
         y = agg1$total[agg1$Group.2 == school.names()[1]], 
         type = "l",
         xlab = "Year",
         ylab = "Total Crimes",
         col = 1)
    lines(x = agg1$Group.1[agg1$Group.2 == school.names()[2]], 
          y = agg1$total[agg1$Group.2 == school.names()[2]],
          col = 2)
    lines(x = agg1$Group.1[agg1$Group.2 == school.names()[3]], 
          y = agg1$total[agg1$Group.2 == school.names()[3]],
          col = 3)
    legend("topright", col = c(1:length(unique(input$show_schools))), 
            lty = rep(1,length(unique(input$show_schools))), 
           legend = unique(input$show_schools))
```